# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labworks', '0014_auto_20160503_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubjectmembership',
            name='date_end',
            field=models.DateField(null=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbe\xd0\xba\xd0\xbe\xd0\xbd\xd1\x87\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'),
        ),
        migrations.AddField(
            model_name='teachersubjectmembership',
            name='date_start',
            field=models.DateField(null=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbd\xd0\xb0\xd1\x87\xd0\xb0\xd0\xbb\xd0\xb0'),
        ),
    ]
